project:
  type: website
  output-dir: docs

website:
  title: "Selina Cheng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: stats20.qmd
        text: STATS20

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

